; ============================================================
;  PSTI – Energy Monitoring & Relay Control
;  Board : ESP32 DevKit V1 / V4 (38-pin WROOM-32)
;  Sensor: PZEM-004T v3.0
;  Relay : 4-Channel (Pin 14, 25, 26, 27)
; ============================================================

[env:esp32dev]
platform  = espressif32@^6.6.0
board     = esp32dev
framework = arduino

; Serial monitor
monitor_speed   = 115200
monitor_filters = esp32_exception_decoder, default

; Library dependencies
lib_deps =
    mandulaj/PZEM-004T-v30@^1.1.2
    bblanchon/ArduinoJson@^7.2.1
    EspSoftwareSerial

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0

; Upload (aktifkan jika auto-detect gagal, ganti COM5 sesuai PC Anda)
upload_port   = COM4
monitor_port  = COM4
